config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "toppages#index"
  root to: "tasks#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"  

  resources :users
  resources :tasks
  
#---------------------------------------
#  resources :users, only: [:index, :show, :create]
#  resources :tasks, only: [:create, :destroy]
#---------------------------------------  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end  

  def counts(user)
    @count_tasks = user.tasks.count
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end
  
  def show
#    redirect_to root_url    
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end    
  end

  def new
    @task = Task.new
#    @task = current_user.tasks.build(task_params)  
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task が正常に投稿されました。"
      redirect_to @task
    else
#    @pagy, @tasks = pagy(current_user.tasks.order(id: :desc))      
      flash.now[:danger] = "Task が投稿されませんでした。"
      render :new
    end
  end

  def edit
#    correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end    
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task は正常に更新されました。"
      redirect_to @task
    else
      flash.now[:danger] = "Task は更新されませんでした。"
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task は正常に削除されました。"
    redirect_to tasks_url
#    redirect_back(fallback_location: root_path)
  end
  
  private

  def set_task
#    @task = Task.find(params[:id])
    @task = Task.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    # ログインユーザ以外だったらrootに行く
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
#    @pagy, @users = pagy(User.order(id: :desc), items: 25)
  end

  def show
    @user = User.find(params[:id])
#    @pagy, @tasks = pagy(@user.tasks.order(id: :desc))
#    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました。"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Kadai-Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body class="container">
    <!-- ヘッダー -->
    <table border="0">
    <tr>
      <th><h4>Kadai-Tasklist</h4></th>
      <% if logged_in? %>
        <td> ｜ </td>
        <td><%= current_user.name %></td>
      <% end %>
    </tr>
    </table>

    <!-- メイン -->
    <div class="container">
      <%= render "layouts/flash_messages" %>
    
      <%= yield %>
    </div>    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :status, "ステータス"%>
  <%= f.text_field :status %>
  
  <%= f.label :content, "タスク"%>
  <%= f.text_field :content %>

  <%= f.submit "投稿" %>

<% end %>  

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
  <% tasks.each do |task| %>
    <% if current_user == task.user %>
    <table border="0">
    <tr>
      <td><%= task.user.name %> ｜ <%= task.created_at %></td>
    </tr>
    <tr>
      <td><h3><%= link_to task.id, task_path(task) %>：<%= task.status %>｜<%= task.content %></h3></td>
    </tr>
    </table>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Task-id: <%= @task.id %>　編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", root_path %> ｜ <%= link_to "削除する", @task, method: :delete, data: { confirm: "本当に削除してよろしいですか？" } %>

app/views/tasks/index.html.erb
<%= render 'tasks', tasks: @tasks %>

<!-- 新規タスクの投稿 -->
<%= link_to "新規タスクの投稿", new_task_path %> ｜ 
<!-- ログアウト -->
<%= link_to "ログアウト", logout_path, method: :delete %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>

<p>ステータス: <%= @task.status %></p>
<p>タスク: <%= @task.content %></p>

<%= link_to "一覧に戻る", root_path %> ｜ 
<%= link_to "編集する", edit_task_path(@task) %> ｜ 
<%= link_to "削除する", @task, method: :delete, data: { confirm: "本当に削除してよろしいですか？" } %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_with(model: @user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <table border="0">
    <tr>
      <th><%= f.label :name, "Name" %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    
    <tr>
      <th><%= f.label :email, "Email" %></th>
      <td><%= f.email_field :email %></td>
    </tr>
    
    <tr>
      <th><%= f.label :password, "Password" %></th>
      <td><%= f.password_field :password %></td>
    </tr>
    
    <tr>
      <th><%= f.label :password_confirmation, "Confirmation" %></th>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
  </table>

  <%= f.submit "登録する" %>
<% end %>

<%= link_to "戻る", root_path %>